import type { Metadata } from "next";
import localFont from "next/font/local";

import AppSidebar from "@/components/app-sidebar";


import "./globals.css";

import "primereact/resources/themes/lara-light-blue/theme.css";
import 'primeicons/primeicons.css';
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DWH Management Console",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >       
        {children}
      </body>
    </html>
  );
}


